dependencies {
    // Configuration
    jarJar(api(forge.configuration.get()))

    // RegistryLib + MapleUtilLib
    implementation(forge.registrylib)
    implementation(forge.mapleutillib)

    compileOnly(forge.ldlib2)
    localRuntime(forge.ldlib2)

    // Recipe Viewers
    compileOnly(forge.bundles.jei)
    localRuntime(forge.bundles.jei)

    compileOnly(forge.jade)
    localRuntime(forge.jade)

    extraLocalRuntime(forge.bundles.extraMystical)
    extraLocalRuntime(forge.bundles.extraMystical)
}
