dependencies {
    implementation(forge.configuration)

    // RegistryLib + MapleUtilLib
    implementation(forge.registrylib)
    implementation(forge.mapleutillib)

    compileOnly(forge.ldlib2)
    localRuntime(forge.ldlib2)

    // Recipe Viewers
    compileOnly(forge.bundles.jei)
    localRuntime(forge.bundles.jei)

    compileOnly(forge.jade)
    localRuntime(forge.jade)

    // localRuntime(forge.bundles.extraMystical)
    // localRuntime(forge.ae2)

    configurations.configureEach {
        exclude group: 'xaero.lib'
        exclude group: 'curse.maven'
        exclude group: 'info.journeymap'
        exclude group: 'cc.tweaked'
        exclude group: 'top.theillusivec4.curios'
        exclude group: 'dev.ftb.mods'
        exclude group: 'dev.architectury'
    }

    compileOnly(forge.create)
    compileOnly(forge.mekanism)

    // localRuntime(forge.create)
    // localRuntime(forge.mekanism)
}
