org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

systemProp.https.protocols=TLSv1.2,TLSv1.3

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.78
neo_version_range=[26.1.2,)

mod_version=2.1.1
mod_id=resource_farm
mod_name=ResourceFarm
mod_group_id=com.maple.resource_farm
mod_description=
mod_url=https://github.com/wanggugu197/Resource-Farm
mod_issue_tracker=https://github.com/wanggugu197/Resource-Farm/issues
mod_authors=maple197
mod_license=GNU Lesser General Public License v3
