package com.maple.resource_farm.api.ResourceTree;

import net.minecraft.resources.Identifier;

public record ResourceTreeType(
                               String type,
                               Identifier sapling,
                               Identifier saplingOverlay,
                               Identifier leaves,
                               Identifier leavesOverlay,
                               Identifier log,
                               Identifier logTop,
                               Identifier strippedLog,
                               Identifier strippedLogTop,
                               Identifier planks,
                               Identifier resin,
                               Identifier resinOverlay,
                               Identifier fruit,
                               Identifier fruitOverlay,
                               Identifier clump,
                               Identifier clumpOverlay,
                               String saplingTranslateKey,
                               String leavesTranslateKey,
                               String logTranslateKey,
                               String strippedLogTranslateKey,
                               String woodTranslateKey,
                               String strippedWoodTranslateKey,
                               String planksTranslateKey,
                               String resinTranslateKey,
                               String fruitTranslateKey,
                               String clumpTranslateKey) {

    public static ResourceTreeType of(String type,
                                      Identifier sapling,
                                      Identifier saplingOverlay,
                                      Identifier leaves,
                                      Identifier leavesOverlay,
                                      Identifier log,
                                      Identifier logTop,
                                      Identifier strippedLog,
                                      Identifier strippedLogTop,
                                      Identifier planks,
                                      Identifier resin,
                                      Identifier resinOverlay,
                                      Identifier fruit,
                                      Identifier fruitOverlay,
                                      Identifier clump,
                                      Identifier clumpOverlay,
                                      String saplingTranslateKey,
                                      String leavesTranslateKey,
                                      String logTranslateKey,
                                      String strippedLogTranslateKey,
                                      String woodTranslateKey,
                                      String strippedWoodTranslateKey,
                                      String planksTranslateKey,
                                      String resinTranslateKey,
                                      String fruitTranslateKey,
                                      String clumpTranslateKey) {
        return new ResourceTreeType(type,
                sapling, saplingOverlay,
                leaves, leavesOverlay,
                log, logTop,
                strippedLog, strippedLogTop,
                planks,
                resin, resinOverlay,
                fruit, fruitOverlay,
                clump, clumpOverlay,
                saplingTranslateKey,
                leavesTranslateKey,
                logTranslateKey,
                strippedLogTranslateKey,
                woodTranslateKey,
                strippedWoodTranslateKey,
                planksTranslateKey,
                resinTranslateKey,
                fruitTranslateKey,
                clumpTranslateKey);
    }
}
