[versions]
configuration = "4.1.2+26.1.2"

registryLib = "8.0.15"
mapleutillib = "0.2.3"
ldlib2 = "26.1.2.29"

jei = "29.16.0.48"
jade = "26.1.8+neoforge"

[libraries]
configuration       = { module = "dev.toma.configuration:configuration-neoforge", version.ref = "configuration" }

# https://maven.gtodyssey.com/#/releases/com/gto/registrylib-neoforge-26.1.2
registrylib = { group = "com.gto", name = "registrylib-neoforge-26.1.2", version.ref = "registryLib" }
# https://maven.gtodyssey.com/#/releases/com/maple197/MapleUtilLib-neoforge-26.1.2
mapleutillib = { group = "com.maple197", name = "MapleUtilLib-neoforge-26.1.2", version.ref = "mapleutillib" }

# https://maven.firstdark.dev/#/snapshots/com/lowdragmc/ldlib2/ldlib2-neoforge-26.1
ldlib2 = { group = "com.lowdragmc.ldlib2", name = "ldlib2-neoforge-26.1", version.ref = "ldlib2" }

jei-neoforge-api    = { module = "mezz.jei:jei-26.1.2-neoforge-api", version.ref = "jei" }
jei-neoforge-impl   = { module = "mezz.jei:jei-26.1.2-neoforge", version.ref = "jei" }

jade                = { module = "maven.modrinth:jade", version.ref = "jade" }

[bundles]
jei = ["jei-neoforge-api", "jei-neoforge-impl"]
