[versions]
configuration = "3.1.1"

registryLib = "8.0.16"
mapleutillib = "0.3.0"
ldlib2 = "2.2.37"

jei = "19.44.0.406"
jade = "15.10.0+neoforge"

cucumber = "1.21.1-8.0.16"
mysticalagriculture = "1.21.1-8.0.27"
mysticalagradditions = "1.21.1-8.0.14"
mysticalautomation = "1.21.1-1.0.6"

ae2 = "19.2.17"

create_version = "6.0.9-215"
mekanism_version = "1.21.1-10.7.19.85"

[libraries]
configuration       = { module = "com.maple.deps:configuration-neoforge", version.ref = "configuration" }

# https://maven.gtodyssey.com/#/releases/com/gto/registrylib-neoforge-1.21.1
registrylib = { group = "com.gto", name = "registrylib-neoforge-1.21.1", version.ref = "registryLib" }
# https://maven.gtodyssey.com/#/releases/com/maple197/MapleUtilLib-neoforge-1.21.1
mapleutillib = { group = "com.maple197", name = "MapleUtilLib-neoforge-1.21.1", version.ref = "mapleutillib" }

# https://maven.firstdark.dev/#/snapshots/com/lowdragmc/ldlib2/ldlib2-neoforge-1.21.1
ldlib2 = { group = "com.lowdragmc.ldlib2", name = "ldlib2-neoforge-1.21.1", version.ref = "ldlib2" }

jei-neoforge-api    = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge-impl   = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }

jade                = { module = "maven.modrinth:jade", version.ref = "jade" }

# https://maven.blakesmods.com/#/releases/com/blakebr0/cucumber/Cucumber
cucumber = { group = "com.blakebr0.cucumber", name = "Cucumber", version.ref = "cucumber" }
# https://maven.blakesmods.com/#/releases/com/blakebr0/mysticalagriculture/MysticalAgriculture
mysticalagriculture = { group = "com.blakebr0.mysticalagriculture", name = "MysticalAgriculture", version.ref = "mysticalagriculture" }
# https://maven.blakesmods.com/#/releases/com/blakebr0/mysticalagradditions/MysticalAgradditions
mysticalagradditions = { group = "com.blakebr0.mysticalagradditions", name = "MysticalAgradditions", version.ref = "mysticalagradditions" }
# https://maven.blakesmods.com/#/releases/com/blakebr0/mysticalautomation/MysticalAutomation
mysticalautomation = { group = "com.blakebr0.mysticalautomation", name = "MysticalAutomation", version.ref = "mysticalautomation" }

# https://central.sonatype.com/artifact/org.appliedenergistics/appliedenergistics2
ae2 = { group = "org.appliedenergistics", name = "appliedenergistics2", version.ref = "ae2" }

# https://maven.createmod.net/com/simibubi/create/create-1.21.1
create = { group = "com.simibubi.create", name = "create-1.21.1", version.ref = "create_version" }
# https://modmaven.dev/mekanism/Mekanism/
mekanism = { group = "mekanism", name = "Mekanism", version.ref = "mekanism_version" }

[bundles]
jei = ["jei-neoforge-api", "jei-neoforge-impl"]

extraMystical = ["cucumber", "mysticalagriculture", "mysticalagradditions", "mysticalautomation"]
