package com.resource_farm.api.ResourceTree;

import net.minecraft.resources.ResourceLocation;

public record ResourceTreeType(
                               String type,
                               ResourceLocation sapling,
                               ResourceLocation saplingOverlay,
                               ResourceLocation leaves,
                               ResourceLocation leavesOverlay,
                               ResourceLocation log,
                               ResourceLocation logTop,
                               ResourceLocation strippedLog,
                               ResourceLocation strippedLogTop,
                               ResourceLocation planks,
                               ResourceLocation resin,
                               ResourceLocation resinOverlay,
                               ResourceLocation fruit,
                               ResourceLocation fruitOverlay,
                               ResourceLocation clump,
                               ResourceLocation clumpOverlay,
                               String saplingTranslateKey,
                               String leavesTranslateKey,
                               String logTranslateKey,
                               String strippedLogTranslateKey,
                               String woodTranslateKey,
                               String strippedWoodTranslateKey,
                               String planksTranslateKey,
                               String resinTranslateKey,
                               String fruitTranslateKey,
                               String clumpTranslateKey) {

    public static ResourceTreeType of(String type,
                                      ResourceLocation sapling,
                                      ResourceLocation saplingOverlay,
                                      ResourceLocation leaves,
                                      ResourceLocation leavesOverlay,
                                      ResourceLocation log,
                                      ResourceLocation logTop,
                                      ResourceLocation strippedLog,
                                      ResourceLocation strippedLogTop,
                                      ResourceLocation planks,
                                      ResourceLocation resin,
                                      ResourceLocation resinOverlay,
                                      ResourceLocation fruit,
                                      ResourceLocation fruitOverlay,
                                      ResourceLocation clump,
                                      ResourceLocation clumpOverlay,
                                      String saplingTranslateKey,
                                      String leavesTranslateKey,
                                      String logTranslateKey,
                                      String strippedLogTranslateKey,
                                      String woodTranslateKey,
                                      String strippedWoodTranslateKey,
                                      String planksTranslateKey,
                                      String resinTranslateKey,
                                      String fruitTranslateKey,
                                      String clumpTranslateKey) {
        return new ResourceTreeType(type,
                sapling, saplingOverlay,
                leaves, leavesOverlay,
                log, logTop,
                strippedLog, strippedLogTop,
                planks,
                resin, resinOverlay,
                fruit, fruitOverlay,
                clump, clumpOverlay,
                saplingTranslateKey,
                leavesTranslateKey,
                logTranslateKey,
                strippedLogTranslateKey,
                woodTranslateKey,
                strippedWoodTranslateKey,
                planksTranslateKey,
                resinTranslateKey,
                fruitTranslateKey,
                clumpTranslateKey);
    }
}
