modLoader = "javafml"
loaderVersion = "[4,)"
minecraftVersion = "${minecraft_version}"
neoVersion = "${neo_version}"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "icon.png"
displayURL = "${mod_url}"
credits = ""

[[mixins]]
config = "resource_farm.mixins.json"

